import type { Lab } from "../types";

export const lab: Lab = {
    id: "peering-not-transitive",
    code: "INC-4102",
    title: "Spoke-a não fala com spoke-b via hub",
    difficulty: "cne",
    technologies: ["peering", "vnet", "route-table", "private-ip"],
    severity: "Sev2",
    etaMin: 22,
    ticket: {
      title: "vm-a (10.1.2.4) timeout para vm-b (10.2.2.4)",
      reporter: "Arquitetura Cloud",
      service: "hub-spoke production",
      openedAt: "2026-08-27T08:00:00-03:00",
      description:
        "Dois spokes peerados com o hub. allowForwardedTraffic=true nos quatro peerings. Ambos pingam o hub. Spoke-a não pinga spoke-b. O time espera transitivity porque 'o hub está no meio'.",
      symptoms: [
        "vm-a → vm-hub-jump ok",
        "vm-b → vm-hub-jump ok",
        "vm-a → vm-b timeout",
        "Nenhum NVA/Firewall no hub encaminhando",
      ],
      impact: "Microsserviço de billing no spoke-b inacessível para o frontend no spoke-a.",
      lastChange: "Landing zone hub-spoke v1 sem vWAN nem gateway transit.",
    },
    topology: {
      nodes: [
        { id: "sa", kind: "vnet", label: "vnet-spoke-a  10.1.0.0/16", x: 4, y: 30, w: 28, h: 46 },
        { id: "hub", kind: "vnet", label: "vnet-hub  10.0.0.0/16", x: 36, y: 22, w: 28, h: 56 },
        { id: "sb", kind: "vnet", label: "vnet-spoke-b  10.2.0.0/16", x: 68, y: 30, w: 28, h: 46 },
        { id: "vma", kind: "vm", label: "vm-a", sublabel: "10.1.2.4", x: 16, y: 54, status: "error", parentId: "sa" },
        { id: "vmh", kind: "vm", label: "vm-hub-jump", sublabel: "10.0.2.10", x: 50, y: 54, status: "ok", parentId: "hub" },
        { id: "vmb", kind: "vm", label: "vm-b", sublabel: "10.2.2.4", x: 82, y: 54, status: "error", parentId: "sb" },
      ],
      edges: [
        { from: "vma", to: "vmh", kind: "ok" },
        { from: "vmb", to: "vmh", kind: "ok" },
        { from: "vma", to: "vmb", kind: "blocked", label: "não transitivo" },
      ],
    },
    world: {
      subscription: "Contoso Connectivity",
      subscriptionId: "a1b2c3d4-0011-4e11-9c01-trans",
      resourceGroup: "rg-hub",
      location: "brazilsouth",
      vnets: [
        {
          name: "vnet-hub",
          space: ["10.0.0.0/16"],
          subnets: [{ name: "snet-shared", prefix: "10.0.2.0/24" }],
        },
        {
          name: "vnet-spoke-a",
          space: ["10.1.0.0/16"],
          subnets: [{ name: "snet-a", prefix: "10.1.2.0/24" }],
        },
        {
          name: "vnet-spoke-b",
          space: ["10.2.0.0/16"],
          subnets: [{ name: "snet-b", prefix: "10.2.2.0/24" }],
        },
      ],
      nsgs: [],
      routeTables: [],
      vms: [
        {
          name: "vm-a",
          os: "linux",
          vnet: "vnet-spoke-a",
          subnet: "snet-a",
          privateIp: "10.1.2.4",
          nic: "nic-a",
          power: "VM running",
          size: "Standard_B2s",
        },
        {
          name: "vm-hub-jump",
          os: "linux",
          vnet: "vnet-hub",
          subnet: "snet-shared",
          privateIp: "10.0.2.10",
          nic: "nic-hub-jump",
          power: "VM running",
          size: "Standard_B2s",
        },
        {
          name: "vm-b",
          os: "linux",
          vnet: "vnet-spoke-b",
          subnet: "snet-b",
          privateIp: "10.2.2.4",
          nic: "nic-b",
          power: "VM running",
          size: "Standard_B2s",
        },
      ],
      peerings: [
        {
          name: "a-to-hub",
          vnet: "vnet-spoke-a",
          remote: "vnet-hub",
          allowForwarded: true,
          allowGateway: false,
          useRemoteGw: false,
          state: "Connected",
        },
        {
          name: "hub-to-a",
          vnet: "vnet-hub",
          remote: "vnet-spoke-a",
          allowForwarded: true,
          allowGateway: false,
          useRemoteGw: false,
          state: "Connected",
        },
        {
          name: "b-to-hub",
          vnet: "vnet-spoke-b",
          remote: "vnet-hub",
          allowForwarded: true,
          allowGateway: false,
          useRemoteGw: false,
          state: "Connected",
        },
        {
          name: "hub-to-b",
          vnet: "vnet-hub",
          remote: "vnet-spoke-b",
          allowForwarded: true,
          allowGateway: false,
          useRemoteGw: false,
          state: "Connected",
        },
      ],
      lbs: [],
      firewalls: [],
      vpns: [],
      dnsZones: [],
      publicIps: [],
    },
    connectivity: [
      { from: "vm-a", to: "10.0.2.10", proto: "icmp", result: "ok" },
      { from: "vm-b", to: "10.0.2.10", proto: "icmp", result: "ok" },
      { from: "vm-a", to: "10.2.2.4", proto: "icmp", result: "no-route", note: "peering não transitivo" },
      { from: "vm-b", to: "10.1.2.4", proto: "icmp", result: "no-route" },
    ],
    hypotheses: [
      { id: "a", label: "Falta allowForwardedTraffic no peering", correct: false },
      { id: "b", label: "VNet peering não é transitivo; spoke-spoke exige NVA/vWAN/gateway", correct: true },
      { id: "c", label: "NSG DenyAll entre 10.1.0.0/16 e 10.2.0.0/16", correct: false },
      { id: "d", label: "Overlap entre spoke-a e spoke-b", correct: false },
    ],
    hints: [
      "Effective routes de nic-a incluem 10.0.0.0/16 (hub) e não incluem 10.2.0.0/16.",
      "allowForwardedTraffic permite que um NVA no hub encaminhe. Sem NVA, não cria magia spoke-to-spoke.",
      "Peering A-hub e B-hub nunca instala rotas A↔B. É uma limitação do produto, não um misconfig pontual de flag.",
    ],
    debrief: {
      rootCause:
        "VNet peering não é transitivo. Spoke-a aprende só o prefixo do hub; spoke-b idem. allowForwardedTraffic só autoriza um hop (NVA/firewall) a encaminhar. Sem appliance, gateway transit ou vWAN, spoke-spoke não existe.",
      solution:
        "Implante Azure Firewall / NVA no hub com UDR nos spokes (0.0.0.0/0 ou prefixos dos outros spokes), ou Virtual WAN, ou peering mesh (não escala).",
      commands: [
        "az network nic show-effective-route-table -g rg-spoke-a --nic-name nic-a -o table",
        "az network vnet peering list -g rg-hub --vnet-name vnet-hub -o table",
        "az network route-table route list -g rg-spoke-a --route-table-name rt-spoke-a",
      ],
      conceptTitle: "Hub-spoke e não-transitividade",
      concept:
        "Peering é um adjacência L3 de um hop. Transitivity exige um dispositivo que encaminhe (Azure Firewall, NVA, vWAN hub). Flags allowGatewayTransit/useRemoteGateways servem a gateway, não a peering puro.",
      prevention:
        "Arquitetura: firewall no hub como default. Documente que 'hub-spoke' sem NVA só entrega spoke↔hub. Teste de aceite inclui spoke-spoke, não só spoke-hub.",
    },
  };
